### ISSUE TITLE
HMAC контейнера

### ISSUE THREAD

**Issue by li0ard** [kmvi/cp-extract-data#1]
Приветствую, благодарю за ваш труд! Не могли бы вы подсказать, если знаете, как генерируется HMAC контейнера (тот что лежит в header.key в самом низу ASN.1 конструкции)?

Заранее спасибо!

**Comment by kmvi** [comment]
Здравствуйте, этим вопросом не занимался, но, может быть, [эта](https://github.com/rudonick/crypto/blob/master/gostKeys.js#L868) библиотека делает то, что нужно?

**Comment by li0ard** [comment]
К сожалению данная библиотека считает некорректно, да и не обновляется с 2016 года
